sudo: required
service: 
    - docker

before_install:
    - docker build -t briariy/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true briariy/docker-react npm run test -- --coverage
